### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by peterj** [piumaio/piuma#11]
Since tool requirest ```pngquant``` and ```jpegoptim```, it would make sense to have a Docker image with those tools installed already and running the tool would be even easier.

**Comment by hwchiu** [comment]
Hi, I would like to help this issue.

**Comment by Remeic** [comment]
@hwchiu Sure no problem, i assign this to you!

**Comment by hwchiu** [comment]
@aranajhonny thanks!!
It seems you have done the docker image.
@Remeic I think it's better to link github account to docker hub to trigger automatically build procedure for piuma server.
And we can also update READEME.md after the public docker image has been created.

**Comment by peterj** [comment]
@hwchiu looks like the PR for adding the Dockerfile was closed but never merged - @aranajhonny are you planning to finish the PR up or should @hwchiu  take it over?

**Comment by Remeic** [comment]
Hi, @peterj can you take over the PR?

**Comment by peterj** [comment]
@Remeic  sure, I already sent out a PR for this - #17
