### ISSUE TITLE
CodeCov Badge

### ISSUE THREAD

**Issue by owanesh** [piumaio/piuma#14]
We use **CodeCov** to test the code coverage.

Do you want to help us put the badge on this project as well?
You will need to edit the .travis.yml file

Try it, and open a PR when you've solved it!

Good fun 👍 

https://codecov.io/gh/lotrekagency

_PS: Do not forget to update the README.md So even other developers will see code coverage, and eventually increase it_

**Comment by dhoeric** [comment]
@Owanesh I can try doing this!

**Comment by owanesh** [comment]
Closed with PR `CodeCov Badge #15`   #15
