### ISSUE TITLE
Using interface/structure to handle multiple image type (jpeg, png)

### ISSUE THREAD

**Issue by hwchiu** [piumaio/piuma#4]
Hi
I found there're too many if/else syntax in optimizer.go to handle different image type.
I think we should use interface/structure to handle those logic and make each image type handler to deal with their own logic.
Do you have any idea about this ? 
If you think that implementation is well and I can help to handle this.

Thanks.

**Comment by astagi** [comment]
Yeah @hwchiu a refactoring using a separate handler would be fantastic!  In that case we could also implement another handler that deals with another format X for example, is that close to your initial idea?

**Comment by hwchiu** [comment]
Yes, That's what I thought and I will send a PR after I finish a refactoring.

Thanks.

**Comment by astagi** [comment]
Awesome @hwchiu thank you :)
